### ISSUE TITLE
博主，非常感谢

### ISSUE THREAD

**Issue by nenhall** [Ruffianjiang/java4fun#1]
还是不会用，我不懂java语言，我的是mac系统，电脑里已经配java环境；我下你`dawn-example`这个工程后，应该进入哪个目录执行某条指令来启动csdn导出功能，请告知，谢谢！

**Comment by Ruffianjiang** [comment]
1、源码打包
mvn package spring-boot:repackage
2、暂时使用 lib\ 下的jar包，后面传到七牛上去

执行 java -jar html2md-0.0.1-SNAPSHOT.jar

访问 http://localhost:8002/tools/csdn4author

**Comment by Ruffianjiang** [comment]
@neghao 
网速比较慢，还在上传
